import { Component } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  constructor(private matIconRegistry: MatIconRegistry, private domSanitizer: DomSanitizer){
    this.matIconRegistry.addSvgIcon(
      'lungs',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/lungs.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'confusion',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/confusion.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'smile',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/smile.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'arrow',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/arrowUp.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'settings',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/settings.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'forest',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/forest.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'arrowOpen',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/arrowOpen.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'arrowRight',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/arrowRight.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'close',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/close.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'lips',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/lips.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'nose',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/nose.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'select',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/select.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'home',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/home.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'menu',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/menu.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'plus',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/plus.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'premium',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/premium.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'cloak',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/cloak.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'wind',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/wind.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'success',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/success.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'help',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/help.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'back',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/back.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'next',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/next.svg")
    );
    this.matIconRegistry.addSvgIcon(
      'lock',
      this.domSanitizer.bypassSecurityTrustResourceUrl("assets/icons/lock.svg")
    );
  }
}